kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-qts-david
  annotations:
    trident.qnap.io/threshold: "90"
    trident.qnap.io/ThinAllocate: "true"
spec:
  accessModes:
    - ReadWriteOnce
#    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: qnap-iscsi

---
apiVersion: v1
kind: Pod
metadata:
  name: storage-test
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - mountPath: /data
          name: test-vol
  volumes:
    - name: test-vol
      persistentVolumeClaim:
        claimName: pvc-qts-david