apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: artifact-registry-helm
  namespace: argocd
spec:
  secretStoreRef:
    name: one-password
    kind: ClusterSecretStore

  target:
    name: artifact-registry-helm
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        type: helm
        url: europe-southwest1-docker.pkg.dev
        username: _json_key
        password: "{{ .gcpSaJson }}"

  data:
    - secretKey: gcpSaJson
      remoteRef:
        key: Jenkins
        property: jenkinsArtifactRegistry.json